name: go-test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout Go Module
        uses: actions/checkout@v4
      - name: Set up go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          check-latest: true
      - name: Dependencies
        run: go get -v -t ./...
      - name: Build and test CLI
        working-directory: ./cmd
        run: |
          go build -v -ldflags "-X main.TheBuilder=$GITHUB_ACTOR -X main.TheVersion=$GITHUB_REF_NAME" -o rmd160
          ./rmd160 --version
          go test -v -timeout 5m ./...
      - name: Test main package
        run: go test -v -timeout 5m ./...
